[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[[edge_functions]]
  function = "auth"
  path = "/"

[[edge_functions]]
  function = "auth"
  path = "/index.html"

[[edge_functions]]
  function = "auth"
  path = "/api/auth"

[[edge_functions]]
  function = "auth"
  path = "/api/admin/change-password"

# No environment variables needed!